//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dieuxe1Entities : DbContext
    {
        public dieuxe1Entities()
            : base("name=dieuxe1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dim_Time> Dim_Time { get; set; }
        public virtual DbSet<tblChiTietChuyenDi> tblChiTietChuyenDis { get; set; }
        public virtual DbSet<tblDangKylich> tblDangKyliches { get; set; }
        public virtual DbSet<tblDangKyLichChiTiet> tblDangKyLichChiTiets { get; set; }
        public virtual DbSet<tblDieuXe> tblDieuXes { get; set; }
        public virtual DbSet<tblLienHe> tblLienHes { get; set; }
        public virtual DbSet<tblLoaiLienHe> tblLoaiLienHes { get; set; }
        public virtual DbSet<tblLoaiXe> tblLoaiXes { get; set; }
        public virtual DbSet<tblNguoiDung> tblNguoiDungs { get; set; }
        public virtual DbSet<tblSearch> tblSearches { get; set; }
        public virtual DbSet<tblXe> tblXes { get; set; }
    
        public virtual int createTableDim_Time()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("createTableDim_Time");
        }
    }
}
