//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_Time
    {
        public System.DateTime Order_Date { get; set; }
        public Nullable<int> Order_Month { get; set; }
        public Nullable<int> Order_Year { get; set; }
        public Nullable<int> Order_Quarter { get; set; }
    }
}
