//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDieuXe
    {
        public int MaDieuxe { get; set; }
        public string NoiDi { get; set; }
        public string NoiDen { get; set; }
        public Nullable<System.TimeSpan> GioDi { get; set; }
        public Nullable<System.TimeSpan> GioVe { get; set; }
        public Nullable<int> TaiXe { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public string TuyenDuongDi { get; set; }
        public string TuyenDuongVe { get; set; }
        public string GhiChu { get; set; }
        public string BienKiemSoat { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapnhat { get; set; }
        public Nullable<System.DateTime> NgayDi { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public string DsDiemDung { get; set; }
    }
}
