//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDangKyLichChiTiet
    {
        public int DangKyLichChiTietId { get; set; }
        public Nullable<int> DangKyLichId { get; set; }
        public string TenNguoiDi { get; set; }
        public Nullable<System.DateTime> ThoiGianDen { get; set; }
        public Nullable<System.DateTime> ThoiGianVe { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<System.TimeSpan> GioDen { get; set; }
        public Nullable<System.DateTime> NgayVe { get; set; }
        public Nullable<System.TimeSpan> GioVe { get; set; }
        public string NoiDi { get; set; }
        public string NoiDen { get; set; }
        public string Ghichu { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapnhat { get; set; }
        public Nullable<int> SoNguoi { get; set; }
        public string ToaDoDi { get; set; }
        public string ToaDoDen { get; set; }
        public string SdtLienLac { get; set; }
    }
}
