//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNguoiDung
    {
        public int NguoiDungID { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public Nullable<int> LienHeId { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> NguoiCapnhat { get; set; }
    }
}
