//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSearch
    {
        public int LienHeId { get; set; }
        public string diadiem { get; set; }
        public Nullable<System.DateTime> NgayLuu { get; set; }
    }
}
